### ISSUE TITLE
Rarity of Pokemon and their Type 

### ISSUE THREAD

**Issue by unseenmagik** [GlobalPlusPlus/RocketMapPlusPlus#27]
**## Expected Behavior**
The rarity and type of the pokemon is obtained and delivered to the Map, this should also be available to pull from the DB and deliver to a webhook. 

**## Current Behavior**
The Rarity and Type are not deliverable via a webhook. 

**## Possible Solution**
Let Bart work his magic

## Context

The information is available on the map. I want to use this information in a webhook.

## Your Environment

* Version used: latest git pull of RM++
* Environment name and version (e.g. Python 2.7): Python2.7 VM Ubuntu 18.04
* Operating System and version (desktop or mobile): Mobile/Discord

**Comment by unseenmagik** [comment]
Thank to Bart for his efforts on this one. This has now been implemented.
Issue can be closed as compete.

**Comment by Bart274** [comment]
I will keep the issue open until I have merged the branch in which I committed the changes, I forgot to create a separate branch for it :-)

**Comment by Bart274** [comment]
solved in https://github.com/GlobalPlusPlus/RocketMapPlusPlus/pull/31
