### ISSUE TITLE
Ability to change HTML Map Name

### ISSUE THREAD

**Issue by unseenmagik** [GlobalPlusPlus/RocketMapPlusPlus#30]
## Expected Behavior
Ability the name your own HTML Map "Title"

## Current Behavior
Currently not able to change the name of the map unless you edit the HTML file directly. 

## Possible Solution
Adding the ability to change the name of the HTML Map from "RocketMapPlusPlus" to whatever you want using a configurable in the config.ini

## Steps to Reproduce (for bugs)
N/A 

## Context
This would offer each user the ability to name their own map to be unique. 

## Your Environment
N/A

**Comment by Bart274** [comment]
Solved in https://github.com/GlobalPlusPlus/RocketMapPlusPlus/pull/32
